//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace KorisnickiInterfejs.WSUniverzitet {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DajSveLeteliceOperationCompleted;
        
        private System.Threading.SendOrPostCallback DajLetelicuOperationCompleted;
        
        private System.Threading.SendOrPostCallback DajRegBrLeteliceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::KorisnickiInterfejs.Properties.Settings.Default.KorisnickiInterfejs_WSUniverzitet_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DajSveLeteliceCompletedEventHandler DajSveLeteliceCompleted;
        
        /// <remarks/>
        public event DajLetelicuCompletedEventHandler DajLetelicuCompleted;
        
        /// <remarks/>
        public event DajRegBrLeteliceCompletedEventHandler DajRegBrLeteliceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DajSveLetelice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DajSveLetelice() {
            object[] results = this.Invoke("DajSveLetelice", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DajSveLeteliceAsync() {
            this.DajSveLeteliceAsync(null);
        }
        
        /// <remarks/>
        public void DajSveLeteliceAsync(object userState) {
            if ((this.DajSveLeteliceOperationCompleted == null)) {
                this.DajSveLeteliceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDajSveLeteliceOperationCompleted);
            }
            this.InvokeAsync("DajSveLetelice", new object[0], this.DajSveLeteliceOperationCompleted, userState);
        }
        
        private void OnDajSveLeteliceOperationCompleted(object arg) {
            if ((this.DajSveLeteliceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DajSveLeteliceCompleted(this, new DajSveLeteliceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DajLetelicu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DajLetelicu(string RegBr) {
            object[] results = this.Invoke("DajLetelicu", new object[] {
                        RegBr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DajLetelicuAsync(string RegBr) {
            this.DajLetelicuAsync(RegBr, null);
        }
        
        /// <remarks/>
        public void DajLetelicuAsync(string RegBr, object userState) {
            if ((this.DajLetelicuOperationCompleted == null)) {
                this.DajLetelicuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDajLetelicuOperationCompleted);
            }
            this.InvokeAsync("DajLetelicu", new object[] {
                        RegBr}, this.DajLetelicuOperationCompleted, userState);
        }
        
        private void OnDajLetelicuOperationCompleted(object arg) {
            if ((this.DajLetelicuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DajLetelicuCompleted(this, new DajLetelicuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DajRegBrLetelice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DajRegBrLetelice(string naziv) {
            object[] results = this.Invoke("DajRegBrLetelice", new object[] {
                        naziv});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DajRegBrLeteliceAsync(string naziv) {
            this.DajRegBrLeteliceAsync(naziv, null);
        }
        
        /// <remarks/>
        public void DajRegBrLeteliceAsync(string naziv, object userState) {
            if ((this.DajRegBrLeteliceOperationCompleted == null)) {
                this.DajRegBrLeteliceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDajRegBrLeteliceOperationCompleted);
            }
            this.InvokeAsync("DajRegBrLetelice", new object[] {
                        naziv}, this.DajRegBrLeteliceOperationCompleted, userState);
        }
        
        private void OnDajRegBrLeteliceOperationCompleted(object arg) {
            if ((this.DajRegBrLeteliceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DajRegBrLeteliceCompleted(this, new DajRegBrLeteliceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DajSveLeteliceCompletedEventHandler(object sender, DajSveLeteliceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DajSveLeteliceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DajSveLeteliceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DajLetelicuCompletedEventHandler(object sender, DajLetelicuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DajLetelicuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DajLetelicuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DajRegBrLeteliceCompletedEventHandler(object sender, DajRegBrLeteliceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DajRegBrLeteliceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DajRegBrLeteliceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591